language: node_js

node_js:
  - "11"

install:
  - npm install

script:
  - npm run build

after_success:
  - rm -rf .git
  - git clone https://${GH_REF} -b ${P_BRANCH} tmp
  - mv tmp/.git dist
  - cd dist
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "build from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_REF} ${P_BRANCH}

branches:
  only:
    - source

notifications:
  email:
    - ${U_EMAIL}
  on_failure: always
